apps/mascotas/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^registrar-mascota$', views.registrar_mascota, name='registrar_mascota'),
    url(r'^mis-mascotas$', views.mascotas_usuario, name='mascotas_usuario'),
    url(r'^mis-mascotas/editar/', views.editar_mascota, name='editar_mascota'),
    url(r'^mis-mascotas/eliminar/', views.eliminar_mascota, name='eliminar_mascota'),
]

project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles import views

urlpatterns = [

    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^users/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="user-logout"),

    url(r'^', include('apps.base.urls', namespace='base_app')),
    url(r'^', include('apps.usuarios.urls', namespace='usuarios_app')),
    url(r'^', include('apps.negocios.urls', namespace='negocios_app')),
    url(r'^', include('apps.mascotas.urls', namespace='mascotas_app')),
    url(r'^', include('apps.publicidad.urls', namespace='publicidad_app')),
    url(r'^', include('apps.pagos.urls', namespace='pagos_app')),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

apps/mascotas/models.py
from django.db import models
from imagekit.models import ProcessedImageField


def imagen_mascota_upload_to(instance, filename):
    return "mascotas/{nombre}/{file}".format(nombre=instance.dueño.email, file=filename)


class Mascota(models.Model):
    dueño = models.ForeignKey('usuarios.Usuario', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=256)
    ESPECIES = ((1, 'Canino'),
                (2, 'Felino'),
                (3, 'Reptil'),
                (4, 'Roedor'),
                (5, 'Anfibio'),
                (6, 'Ave'),
                (7, 'Otro'),
                )
    especie = models.IntegerField(choices=ESPECIES, blank=True, null=True, default=1)
    raza = models.CharField(max_length=256, blank=True)
    imagen = ProcessedImageField(upload_to=imagen_mascota_upload_to,
                                 format='JPEG',
                                 options={'quality': 95})
    SEXOS = ((1, 'Macho'), (2, 'Hembra'))
    sexo = models.PositiveIntegerField(choices=SEXOS)
    fecha_nacimiento = models.DateField(null=True)
    caracteristicas = models.TextField(blank=True)  # color, pelaje, piel, chip, comportamiento,
    desparasitado = models.BooleanField(default=False)
    esterilizado = models.BooleanField(default=False)
    castrado = models.BooleanField(default=False)
    vacunas = models.TextField(blank=True)
    observaciones_medicas = models.TextField(blank=True)

    def __str__(self):
        return self.dueño.email + ': ' + self.nombre

    class Meta:
        verbose_name = 'Mascota'
        verbose_name_plural = 'Mascotas'

    @property
    def get_image_url(self):
        if self.imagen:
            return self.imagen.url
        else:
            from django.contrib.staticfiles.templatetags.staticfiles import static
            return static('base/img/default_pet.png')

apps/mascotas/forms.py
from django import forms

from .models import Mascota


class MascotaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')  # globally override the Django >=1.6 default of ':'
        super(MascotaForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Mascota
        fields = '__all__'
        widgets = {
            'dueño': forms.HiddenInput(),
            'nombre': forms.TextInput(attrs={
                'required': True,
            }),
            'especie': forms.Select(attrs={
                'required': True,
                'class': 'validate'
            }),
            'raza': forms.TextInput(attrs={
                'required': True,
            }),
            'sexo': forms.Select(attrs={
                'required': True,
                'class': 'validate'
            }),
            'imagen': forms.FileInput(attrs={
                'accept': 'image/*',
                'required': False,
                'class': 'validate'
            }),
            'caracteristicas': forms.Textarea(attrs={
                'class': 'materialize-textarea',
            }),
            'vacunas': forms.Textarea(attrs={
                'class': 'materialize-textarea',
            }),
            "observaciones_medicas": forms.Textarea(attrs={
                'class': 'materialize-textarea',
            }),
            'fecha_nacimiento': forms.DateInput(attrs={
                'class': 'datepicker',
                'required': True,
            })
        }

        labels = {
            'dueño': '',
            'fecha_nacimiento': 'Fecha de nacimiento (Aprox)',
            'caracteristicas': 'Características físicas (color, peso, tamaño, etc.)',
            'esterilizado': 'Esterilizado',
            'castrado': 'Castrado',
            'desparasitado': 'Desparasitado',
            'observaciones_medicas': 'Observaciones Médicas'
        }

apps/mascotas/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

from .forms import MascotaForm
from .models import Mascota


@login_required
def mascotas_usuario(request):
    mascotas = Mascota.objects.filter(dueño=request.user)
    return render(request, 'mascotas/mascotas_usuario.html', {'mascotas': mascotas})


@login_required(login_url='/signup')
def registrar_mascota(request):
    mascota_form = MascotaForm(initial={'dueño': request.user.pk}, label_suffix="")
    redirect_to = ''
    if 'next' in request.GET:
        redirect_to = request.GET['next']
    if request.method == 'POST':
        mascota_form = MascotaForm(request.POST, request.FILES, initial={'dueño': request.user.pk})
        if 'redirect_to' in request.POST:
            redirect_to = request.POST['redirect_to']
        if mascota_form.is_valid():
            mascota_form.save()
            if redirect_to != '':
                return HttpResponseRedirect(redirect_to)
            else:
                return redirect(reverse('mascotas_app:mascotas_usuario'))
    return render(request, 'mascotas/registrar_mascota.html', {'form': mascota_form, 'redirect_to': redirect_to})


@login_required
def editar_mascota(request):
    if 'pet' in request.GET:
        try:
            mascota = Mascota.objects.get(id=request.GET.get('pet'))
            mascota_form = MascotaForm(instance=mascota)
            if request.method == 'POST':
                mascota_form = MascotaForm(request.POST, request.FILES, instance=mascota)
                if mascota_form.is_valid():
                    mascota_form.save()
                    return redirect(reverse('mascotas_app:mascotas_usuario'))
            return render(request, 'mascotas/editar_mascota.html', {'form': mascota_form,
                                                                    'id_mascota': mascota.id})

        except Mascota.DoesNotExist as e:
            return redirect(reverse('mascotas_app:mascotas_usuario'))
    else:
        return redirect(reverse('mascotas_app:mascotas_usuario'))


@login_required
def eliminar_mascota(request):
    if request.method == 'POST':
        mascota = get_object_or_404(Mascota, id=request.POST['id_mascota'])
        mascota.delete()
    return redirect(reverse('mascotas_app:mascotas_usuario'))

templates/mascotas/editar_mascota.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}

{% block title %}
    Registra a tu mascota
{% endblock %}


{% block styles %}

{% endblock %}


{% block content %}
    <div class="container">
        <div class="row section">
            <div class="col m12">
                <div class="card">
                    <div class="card-content">
                        <div class="row">
                            <div class="col s12">
                                <h5 class="left">
                                    Edita tu mascota
                                </h5>
                                <form action="{% url 'mascotas_app:eliminar_mascota' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{ id_mascota }}" name="id_mascota">
                                    <a data-target="modal-confirmar-eliminar"
                                       class="btn red right m-t-sm modal-trigger">
                                        <i class="material-icons left">delete</i>Eliminar
                                    </a>
                                    <div id="modal-confirmar-eliminar" class="modal">
                                        <div class="modal-content">
                                            <h4>¿Seguro que deseas eliminar el perfil de ésta mascota?</h4>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit"
                                                    class=" modal-action modal-close waves-effect waves-light btn red">
                                                Aceptar
                                            </button>
                                            <a href="javascript:void(0);"
                                               class=" modal-action modal-close waves-effect waves-red btn-flat">Cancelar</a>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="col s12">
                                <form action="{% url 'mascotas_app:editar_mascota' %}?pet={{ id_mascota }}"
                                      method="POST"
                                      id="form_mascota"
                                      enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form.dueño }}
                                    <div class="row">
                                        <div class="col s12 m6">
                                            <div class="input-field">
                                                {{ form.nombre }}
                                                {{ form.nombre.label_tag }}
                                            </div>
                                            {% for error in form.nombre.errors %}
                                                <label class="perror">{{ error }}</label>
                                            {% endfor %}
                                        </div>
                                        <div class="col s12 m6">
                                            <div class="input-field">
                                                {{ form.fecha_nacimiento }}
                                                {{ form.fecha_nacimiento.label_tag }}
                                            </div>
                                            {% for error in form.fecha_nacimiento.errors %}
                                                <label class="perror">{{ error }}</label>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col s12 m6">
                                            <div class="input-field">
                                                {{ form.especie }}
                                                {{ form.especie.label_tag }}
                                            </div>
                                            {% for error in form.especie.errors %}
                                                <label class="perror">{{ error }}</label>
                                            {% endfor %}
                                        </div>
                                        <div class="col s12 m6">
                                            <div class="input-field">
                                                {{ form.raza }}
                                                {{ form.raza.label_tag }}
                                            </div>
                                            {% for error in form.raza.errors %}
                                                <label class="perror">{{ error }}</label>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col s12 m6">
                                            <div class="input-field">
                                                {{ form.sexo }}
                                                {{ form.sexo.label_tag }}
                                            </div>
                                            {% for error in form.sexo.errors %}
                                                <label class="perror">{{ error }}</label>
                                            {% endfor %}
                                        </div>
                                        <div class="col s12 m6 file-field ">
                                            <div class="input-field">
                                                <div class="btn waves-effect waves-light accent">
                                                    <span>{{ form.imagen.label }}</span>
                                                    {{ form.imagen }}
                                                </div>
                                                <div class="file-path-wrapper">
                                                    <input class="file-path validate" type="text" id="imagen_text"
                                                           placeholder="Actualmente: {{ form.imagen.value }}">
                                                </div>
                                            </div>
                                            {% for error in form.imagen.errors %}
                                                <label class="perror">{{ error }}</label>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col s12 m6 input-field">
                                            <div style="margin-right: 5px;">
                                                {{ form.esterilizado }}
                                                {{ form.esterilizado.label_tag }}
                                            </div>
                                            <div style="margin-right: 5px;">
                                                {{ form.desparasitado }}
                                                {{ form.desparasitado.label_tag }}
                                            </div>
                                            {{ form.castrado }}
                                            {{ form.castrado.label_tag }}
                                        </div>
                                        <div class="col s12 m6">
                                            <div class="input-field">
                                                {{ form.observaciones_medicas }}
                                                {{ form.observaciones_medicas.label_tag }}
                                            </div>
                                            {% for error in form.observaciones_medicas.errors %}
                                                <label class="perror">{{ error }}</label>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col s12 m6">
                                            <div class="input-field">
                                                {{ form.caracteristicas }}
                                                {{ form.caracteristicas.label_tag }}
                                            </div>
                                            {% for error in form.caracteristicas.errors %}
                                                <label class="perror">{{ error }}</label>
                                            {% endfor %}
                                        </div>
                                        <div class="col s12 m6">
                                            <div class="input-field">
                                                {{ form.vacunas }}
                                                {{ form.vacunas.label_tag }}
                                            </div>
                                            {% for error in form.vacunas.errors %}
                                                <label class="perror">{{ error }}</label>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col s12">
                                            <button class="btn right">Guardar</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    <script src="{% static 'base/js/clockpicker/materialize.clockpicker.js' %}"></script>
    <script src="{% static 'base/js/clockpicker/es_ES.js' %}"></script>
    <script>
        var $form = $("#form_mascota");
        $(document).ready(function () {
            Materialize.updateTextFields();
        });
        $('input.datepicker').each(function () {
            $(this).pickadate({
                firstDay: 0,
                formatSubmit: 'yyyy-mm-dd',
                selectMonths: true, // Creates a dropdown to control month
                selectYears: 15 // Creates a dropdown of 15 years to control year
            });
        });
        $form.validate({
            name: "required",
            nombre: {
                minlength: 6
            },
            imagen: {
                required: false
            },
            errorPlacement: function (error, element) {
                error.addClass('perror').insertAfter($(element).closest('.input-field'));
                Materialize.updateTextFields();
            }
        });
        $form.on('submit', function () {
            $('input[name="fecha_nacimiento"]').val($('input[name="fecha_nacimiento_submit"]').val());
        });

    </script>
{% endblock %}

templates/mascotas/mascotas_usuario.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}

{% block title %}
    Tus mascotas
{% endblock %}


{% block styles %}

{% endblock %}


{% block content %}
    <div class="container">
        <div class="row section">
            <div class="col s12">

                <div class="row">
                    {% if not mascotas %}
                        <div class="col s12 hide-on-small-only">
                            <h5>
                                Aún no tienes mascotas registradas
                            </h5>
                            <h6>
                                <a class="hide-on-small-only" href="{% url 'mascotas_app:registrar_mascota' %}">
                                    <i class="material-icons">add</i> Registrar mascota
                                </a>
                            </h6>
                        </div>
                    {% else %}
                        <h5>Tus mascotas</h5>
                        <h6>
                            <a class="hide-on-small-only" href="{% url 'mascotas_app:registrar_mascota' %}">
                                <i class="material-icons">add</i> Registrar mascota
                            </a>
                        </h6>
                        {% for mascota in mascotas %}
                            <div class="div-mascota col s12 m6 l4">
                                <div class="card transparent no-shadow">
                                    <div class="card-content">
                                        <div class="imagen-mascota avatar center-block border p-md"
                                             id="imagen-mascota{{ mascota.id }}">
                                            <style>
                                                #imagen-mascota{{ mascota.id }} {
                                                    background: url({{ mascota.get_image_url }}) center center;
                                                }
                                            </style>
                                        </div>
                                        <div class="info-mascota center-align">
                                            <h5>{{ mascota.nombre }}</h5>
                                        </div>
                                        <div class="actions-mascota center-align">
                                            <a href="{% url 'mascotas_app:editar_mascota' %}?pet={{ mascota.id }}"><i
                                                    class="material-icons">mode_edit</i>Editar</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <div class="col s12 m4 l3 center-align hide-on-med-and-up">
                        <div class="card-content">
                            <a href="{% url 'mascotas_app:registrar_mascota' %}">
                                <h1 class="accent-text">
                                    <i class="material-icons">add</i>
                                </h1>
                                <h5>Registrar mascota</h5>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}

{% endblock %}