apps/mascotas/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^registrar-mascota$', views.registrar_mascota, name='registrar_mascota'),
    url(r'^mis-mascotas$', views.mascotas_usuario, name='mascotas_usuario'),
    url(r'^mis-mascotas/editar/', views.editar_mascota, name='editar_mascota'),
    url(r'^mis-mascotas/eliminar/', views.eliminar_mascota, name='eliminar_mascota'),
]

apps/negocios/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^negocios/$', views.negocios_view, name='negocios'),
    url(r'^negocios/registrar/$', views.registrar_negocio_view, name='registrar_negocio'),

    url(r'^negocios/buscar/$', views.buscar_negocios, name='buscar_negocios'),

    url(r'^negocios/(?P<slug>[\w-]+)/$', views.negocio_view,
        name='negocio_view'),

    url(r'^negocios/(?P<slug>[\w-]+)/dashboard/$', views.dashboard_negocio_view,
        name='dashboard'),

    url(r'^negocios/(?P<slug>[\w-]+)/citas/$', views.citas_negocio_view,
        name='citas'),

    # Calendario y citas
    url(r'^negocios/(?P<slug>[\w-]+)/calendario/$', views.calendario_negocio_view,
        name='calendario'),

    url(r'^citas/api/activar', views.ajax_activar_cita, name='ajax_activar_cita'),
    url(r'^citas/api/rechazar', views.ajax_cancelar_cita, name='ajax_cancelar_cita'),
    url(r'^eventos/api/get', views.ajax_obtener_eventos, name='ajax_obtener_eventos'),
    url(r'^eventos/api/solicitar', views.ajax_solicitar_evento, name='ajax_solicitar_evento'),
    url(r'^eventos/api/create$', views.ajax_crear_evento, name='ajax_crear_evento'),
    url(r'^eventos/api/delete$', views.ajax_eliminar_evento, name='ajax_eliminar_evento'),
    url(r'^eventos/api/update$', views.ajax_actualizar_evento, name='ajax_actualizar_evento'),

    # Configuraciones
    url(r'^negocios/(?P<slug>[\w-]+)/configurar/$', views.configurar_negocio_view,
        name='configurar_negocio'),
    url(r'^negocios/(?P<slug>[\w-]+)/configurar/contacto/$', views.configurar_contacto_negocio_view,
        name='configurar_contacto'),
    url(r'^negocios/(?P<slug>[\w-]+)/configurar/horario/$', views.configurar_horario_negocio_view,
        name='configurar_horario'),
    url(r'^negocios/(?P<slug>[\w-]+)/configurar/servicios/$', views.configurar_servicios_negocio_view,
        name='configurar_servicios'),
    url(r'^negocios/(?P<slug>[\w-]+)/configurar/galeria/$', views.configurar_galeria_negocio_view,
        name='configurar_galeria'),
    url(r'^mis-negocios/$', views.negocios_usuario_view, name='negocios_usuario'),
]

apps/usuarios/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login', views.login_view, name='login'),
    url(r'^signup', views.signup_view, name='signup'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^perfil/$', views.perfil_usuario, name='perfil_usuario'),
    url(r'^perfil/editar$', views.editar_perfil_usuario, name='editar_perfil_usuario'),
    url(r'^mis-citas$', views.citas_usuario, name='citas_usuario'),
    url(r'^suscripcion/beneficios/$', views.beneficios_view, name='beneficios'),
]

project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles import views

urlpatterns = [

    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^users/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="user-logout"),

    url(r'^', include('apps.base.urls', namespace='base_app')),
    url(r'^', include('apps.usuarios.urls', namespace='usuarios_app')),
    url(r'^', include('apps.negocios.urls', namespace='negocios_app')),
    url(r'^', include('apps.mascotas.urls', namespace='mascotas_app')),
    url(r'^', include('apps.publicidad.urls', namespace='publicidad_app')),
    url(r'^', include('apps.pagos.urls', namespace='pagos_app')),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

apps/mascotas/models.py
from django.db import models
from imagekit.models import ProcessedImageField


def imagen_mascota_upload_to(instance, filename):
    return "mascotas/{nombre}/{file}".format(nombre=instance.dueño.email, file=filename)


class Mascota(models.Model):
    dueño = models.ForeignKey('usuarios.Usuario', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=256)
    ESPECIES = ((1, 'Canino'),
                (2, 'Felino'),
                (3, 'Reptil'),
                (4, 'Roedor'),
                (5, 'Anfibio'),
                (6, 'Ave'),
                (7, 'Otro'),
                )
    especie = models.IntegerField(choices=ESPECIES, blank=True, null=True, default=1)
    raza = models.CharField(max_length=256, blank=True)
    imagen = ProcessedImageField(upload_to=imagen_mascota_upload_to,
                                 format='JPEG',
                                 options={'quality': 95})
    SEXOS = ((1, 'Macho'), (2, 'Hembra'))
    sexo = models.PositiveIntegerField(choices=SEXOS)
    fecha_nacimiento = models.DateField(null=True)
    caracteristicas = models.TextField(blank=True)  # color, pelaje, piel, chip, comportamiento,
    desparasitado = models.BooleanField(default=False)
    esterilizado = models.BooleanField(default=False)
    castrado = models.BooleanField(default=False)
    vacunas = models.TextField(blank=True)
    observaciones_medicas = models.TextField(blank=True)

    def __str__(self):
        return self.dueño.email + ': ' + self.nombre

    class Meta:
        verbose_name = 'Mascota'
        verbose_name_plural = 'Mascotas'

    @property
    def get_image_url(self):
        if self.imagen:
            return self.imagen.url
        else:
            from django.contrib.staticfiles.templatetags.staticfiles import static
            return static('base/img/default_pet.png')

apps/pagos/models.py
from django.db import models

# Create your models here.
from apps.usuarios.models import Usuario


class PagosPayPal(models.Model):
    usuario = models.ForeignKey(Usuario)
    fecha = models.DateTimeField(auto_now_add=True)
    paypal_id = models.CharField(max_length=200, default="")
    ajax_peticion = models.TextField(max_length=3000, default="")
    ajax_autorizacion = models.TextField(max_length=3000, default="")
    ajax_confirmacion = models.TextField(max_length=3000, default="")
    estado = models.CharField(max_length=30)

    def __str__(self):
        return str(self.usuario.get_full_name()) + " pago en la fecha" + str(self.fecha) + " - " + str(self.estado)

    class Meta:
        verbose_name = 'Pagos PayPal'
        verbose_name_plural = 'Pagos PayPal'

apps/usuarios/views.py
import logging

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from apps.base.functions import custom_redirect
from apps.usuarios.correos import enviar_correo
from apps.usuarios.models import Usuario
from .forms import LoginForm, SignupForm, UsuarioForm, ContactoSuscripcionForm

logger = logging.getLogger(__name__)


def login_view(request):
    if request.user.is_authenticated():
        return redirect(reverse('base_app:home'))
    login_form = LoginForm()
    redirect_to = ''
    if 'next' in request.GET:
        redirect_to = request.GET['next']
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if 'redirect_to' in request.POST:
            redirect_to = request.POST['redirect_to']
        if login_form.is_valid():
            email = login_form.cleaned_data['email']
            password = login_form.cleaned_data['password']
            user = authenticate(username=email, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    if redirect_to != '':
                        return HttpResponseRedirect(redirect_to)
                    else:
                        return redirect(reverse('usuarios_app:perfil_usuario'))
                else:
                    login_form.add_error(None, 'El usuario no está activo')
                    return render(request, 'usuarios/login.html', {'login_form': login_form,
                                                                   'redirect_to': redirect_to})
            else:
                # Return an 'invalid login' error message.
                login_form.add_error(None, 'Los datos del usuario son inválidos')
                return render(request, 'usuarios/login.html', {'login_form': login_form,
                                                               'redirect_to': redirect_to})
        else:
            return render(request, 'usuarios/login.html', {'login_form': login_form,
                                                           'redirect_to': redirect_to})
    return render(request, 'usuarios/login.html', {'login_form': login_form,
                                                   'redirect_to': redirect_to})


def signup_view(request):
    signup_form = SignupForm()
    redirect_to = ''
    if 'next' in request.GET:
        redirect_to = request.GET['next']
    if request.method == 'POST':
        signup_form = SignupForm(request.POST)
        if 'redirect_to' in request.POST:
            redirect_to = request.POST['redirect_to']
        if signup_form.is_valid():
            email = signup_form.cleaned_data['email']
            password = signup_form.cleaned_data['password']
            Usuario.objects.create_user(email=signup_form.cleaned_data['email'],
                                        password=signup_form.cleaned_data['password'],
                                        nombre=signup_form.cleaned_data['nombre']
                                        )
            enviar_correo(destino=email,
                          asunto='Bienvenido a miPetdate',
                          template='bienvenida')
            user = authenticate(username=email, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    if redirect_to != '':
                        return HttpResponseRedirect(redirect_to)
                    else:
                        return redirect(reverse('usuarios_app:perfil_usuario'))
            return render(request, 'usuarios/login.html', {'signup_form': signup_form,
                                                           'redirect_to': redirect_to})
        else:
            return render(request, 'usuarios/login.html', {'signup_form': signup_form,
                                                           'redirect_to': redirect_to})

    return render(request, 'usuarios/signup.html', {'signup_form': signup_form,
                                                    'redirect_to': redirect_to})


@login_required
def logout_view(request):
    logout(request)
    return redirect(reverse('usuarios_app:login'))


@login_required
def perfil_usuario(request):
    return render(request, 'usuarios/perfil_usuario.html', {'usuario': request.user})


@login_required
def editar_perfil_usuario(request):
    usuario_form = UsuarioForm(instance=request.user)
    if request.method == 'POST':
        usuario_form = UsuarioForm(request.POST, request.FILES, instance=request.user)
        if usuario_form.is_valid():
            usuario_form.save()
            return custom_redirect(reverse('usuarios_app:perfil_usuario'), success='true')
        else:
            pass
    return render(request, 'usuarios/editar_perfil_usuario.html', {'usuario': request.user,
                                                                   'form': usuario_form})


@login_required
def citas_usuario(request):
    from apps.negocios.models import SolicitudEvento
    citas = SolicitudEvento.objects.filter(mascota__dueño=request.user).order_by('-fecha')
    return render(request, 'usuarios/citas_usuario.html', {'citas': citas})


def beneficios_view(request):
    contacto_form = None
    if request.user.is_authenticated():
        contacto_form = ContactoSuscripcionForm(
            initial={'nombre': request.user.get_full_name, 'correo': request.user.email,
                     'telefono': request.user.telefono})
        if request.method == 'POST':

            contacto_form = ContactoSuscripcionForm(request.POST)
            if contacto_form.is_valid():

                contacto = contacto_form.save(commit=False)
                contacto.usuario = request.user
                contacto.save()
                enviar_correo(destino=contacto_form.cleaned_data['correo'],
                              asunto='Contacto de suscripción',
                              template='contacto_suscripcion')
                return custom_redirect(reverse('negocios_app:negocios_usuario'), success='true')
            else:
                return redirect(reverse('usuarios_app:beneficios'))
    return render(request, 'negocios/beneficios.html', {'contacto_form': contacto_form})

templates/usuarios/citas_usuario.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}


{% block title %}

{% endblock %}


{% block styles %}

{% endblock %}


{% block content %}
    <div class="container">
        <div class="row section">
            <div class="col s12">
                <div class="card">
                    <div class="card-content">
                        <h5>
                            Mis solicitudes de cita
                        </h5>
                        {% if citas %}
                            <table class="highlight responsive-table">
                                <thead>
                                <tr>
                                    <th data-field="negocio">Negocio</th>
                                    <th data-field="mascota">Mascota</th>
                                    <th data-field="fecha">Fecha</th>
                                    <th data-field="servicio">Servicio</th>
                                    <th data-field="estado">Estado</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for cita in citas %}
                                    <tr class="pointer">
                                        <td>
                                            <a href="{% url 'negocios_app:negocio_view' cita.negocio.slug %}">{{ cita.negocio.nombre }}</a>
                                        </td>
                                        <td class="modal-trigger" data-target="modal-cita-{{ cita.id }}">
                                            {{ cita.mascota.nombre }}
                                        </td>
                                        <td class="modal-trigger" data-target="modal-cita-{{ cita.id }}">
                                            {{ cita.fecha|date:"SHORT_DATE_FORMAT" }} - {{ cita.fecha|time:"h:i a" }}
                                        </td>
                                        <td class="modal-trigger" data-target="modal-cita-{{ cita.id }}">
                                            {{ cita.servicio.nombre_publico }}
                                        </td>
                                        <td class="modal-trigger" data-target="modal-cita-{{ cita.id }}">
                                            {% if cita.estado == '1' %} <!-- Pendiente -->
                                                <span class="grey lighten-3 white-text p-xs rounded">{{ cita.get_estado_display }}</span>
                                            {% elif cita.estado == '2' %} <!-- Aceptado -->
                                                <span class="green lighten-3 white-text p-xs rounded">{{ cita.get_estado_display }}</span>
                                            {% elif cita.estado == '3' %} <!-- Cancelado -->
                                                <span class="red lighten-3 white-text p-xs rounded">{{ cita.get_estado_display }}</span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                    <div id="modal-cita-{{ cita.id }}" class="modal modal-fixed-footer">
                                        <div class="modal-content">
                                            <h4>Detalles de solicitud de cita</h4>
                                            <div class="row section">
                                                <div class="col s12 m7">
                                                    <div class="row">
                                                        <div class="col s12 m6 center-align">
                                                            <div class="imagen-mascota avatar center-block border p-md"
                                                                 id="imagen-mascota{{ cita.mascota.id }}">
                                                                <style>
                                                                    #imagen-mascota{{ cita.mascota.id }} {
                                                                        background: url({{ cita.get_image_url }}) center center;
                                                                    }
                                                                </style>
                                                            </div>
                                                            <h5>{{ cita.mascota.nombre }}</h5>
                                                        </div>
                                                        <div class="col m6">
                                                            <div class="info-mascota">
                                                                <p>
                                                                    <b>Edad:</b> {{ cita.mascota.fecha_nacimiento|timesince }}
                                                                </p>
                                                                <p><b>Especie:</b> {{ cita.mascota.especie }}</p>
                                                                <p><b>Raza:</b> {{ cita.mascota.raza }}</p>
                                                                <p><b>Sexo:</b> {{ cita.mascota.get_sexo_display }}</p>
                                                                <ul>
                                                                    <li>
                                                                        {% if cita.mascota.esterilizado %}
                                                                            <i class="material-icons green-text">check</i>
                                                                        {% else %}
                                                                            <i class="material-icons red-text">close</i>
                                                                        {% endif %}
                                                                        Esterilizado
                                                                    </li>
                                                                    <li>
                                                                        {% if cita.mascota.castrado %}
                                                                            <i class="material-icons green-text">check</i>
                                                                        {% else %}
                                                                            <i class="material-icons red-text">close</i>
                                                                        {% endif %}
                                                                        Castrado
                                                                    </li>
                                                                    <li>
                                                                        {% if cita.mascota.desparasitado %}
                                                                            <i class="material-icons green-text">check</i>
                                                                        {% else %}
                                                                            <i class="material-icons red-text">close</i>
                                                                        {% endif %}
                                                                        Desparasitado
                                                                    </li>
                                                                </ul>
                                                            </div>
                                                        </div>
                                                        <div class="col s12">
                                                            {% if cita.mascota.caracteristicas %}
                                                                <p><b>Características:</b></p>
                                                                <p>{{ cita.mascota.caracteristicas }}</p>
                                                            {% endif %}
                                                            {% if cita.mascota.observaciones_medicas %}
                                                                <p><b>Observaciones médicas:</b></p>
                                                                <p>{{ cita.mascota.observaciones_medicas }}</p>
                                                            {% endif %}
                                                            {% if cita.mascota.vacunas %}
                                                                <p><b>Vacunas:</b></p>
                                                                <p>{{ cita.mascota.vacunas }}</p>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col s12 m5">
                                                    <p><b>Usuario: </b></p>
                                                    <p>{{ cita.mascota.dueño.get_full_name }}</p>
                                                    <p><b>Mascota:</b></p>
                                                    <p>{{ cita.mascota.nombre }}</p>
                                                    <p><b>Fecha para cita:</b></p>
                                                    <p>{{ cita.fecha|date:"SHORT_DATE_FORMAT" }} -
                                                        {{ cita.fecha|time:"h:i a" }}</p>
                                                    <p><b>Servicio:</b></p>
                                                    <p>{{ cita.servicio.nombre_publico }}</p>
                                                    <p><b>Estado de la solicitud:</b></p>
                                                    <p class="m-t-xs">
                                                        {% if cita.estado == '1' %} <!-- Pendiente -->
                                                            <span class="grey lighten-3 white-text p-xs rounded">{{ cita.get_estado_display }}</span>
                                                        {% elif cita.estado == '2' %} <!-- Aceptado -->
                                                            <span class="green lighten-3 white-text p-xs rounded">{{ cita.get_estado_display }}</span>
                                                        {% elif cita.estado == '3' %} <!-- Cancelado -->
                                                            <span class="red lighten-3 white-text p-xs rounded">{{ cita.get_estado_display }}</span>
                                                        {% endif %}
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <a href="javascript:void(0);"
                                               class=" modal-action modal-close waves-effect waves-red btn-flat">Cerrar</a>
                                        </div>
                                    </div>
                                {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                            <p>No tienes solicitudes de cita. <a class="link"
                                                                 href="{% url 'negocios_app:buscar_negocios' %}">Busca
                                negocios</a> para realizar una</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}

{% endblock %}

templates/usuarios/perfil_usuario.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}


{% block title %}
    Mi perfil
{% endblock %}



{% block styles %}
    <style>
        .card-content {
            border: 1px solid transparent;
            border-radius: 6px;
        }

        .card-content:hover {
            border: 1px solid #E0E0E0;
            border-radius: 6px;
        }
    </style>
{% endblock %}



{% block content %}
    <div class="container">
        <div class="row section m-b-none">
            <div class="col s12 center-align m-t-xl">
                <div class="imagen-usuario avatar center-block border p-md"
                     id="imagen-usuario">
                    <style>
                        #imagen-usuario {
                            background: url({{ user.get_image_url }}) center center;
                        }
                    </style>
                </div>
                <h4>{{ usuario.get_full_name }}</h4>
            </div>
        </div>
        <div class="row row-centered" id="row-acciones">
            <div class="col s6 m4 l3 col-centered">
                <a href="{% url 'mascotas_app:mascotas_usuario' %}">
                    <div class="card transparent no-shadow">
                        <div class="card-content center-align p-tb-lg">
                            <h1 class="no-margins brown-text">
                                <i class="material-icons">pets</i>
                            </h1>
                            <h5 class="black-text">
                                Mis mascotas
                            </h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col s6 m4 l3 col-centered">
                <a href="{% url 'usuarios_app:citas_usuario' %}">
                    <div class="card transparent no-shadow">
                        <div class="card-content center-align p-tb-lg">
                            <h1 class="no-margins rank-text">
                                <i class="material-icons">event</i>
                            </h1>
                            <h5 class="black-text">
                                Mis citas
                            </h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col s6 m4 l3 col-centered" id="col-negocios">
                <a href="{% url 'negocios_app:negocios_usuario' %}">
                    <div class="card transparent no-shadow">
                        <div class="card-content center-align p-tb-lg">
                            <h1 class="no-margins action-text">
                                <i class="material-icons">business</i>
                            </h1>
                            <h5 class="black-text">
                                Mis negocios
                            </h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col s6 m4 l3 col-centered">
                <a href="{% url 'usuarios_app:editar_perfil_usuario' %}">
                    <div class="card transparent no-shadow">
                        <div class="card-content center-align p-tb-lg">
                            <h1 class="no-margins accent-text">
                                <i class="material-icons">mode_edit</i>
                            </h1>
                            <h5 class="black-text">
                                Editar perfil
                            </h5>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
{% endblock %}



{% block scripts %}

    {% if usuario.tiene_negocios %}
        <script>
            $('#col-negocios').prependTo('#row-acciones');
        </script>
    {% endif %}

    <script>
        $(document).ready(function () {
            if (getUrlParameter('success') === 'true') {
                var $toastContent = $('<span><i class="material-icons">check</i> Se ha guardado correctamente</span>');
                Materialize.toast($toastContent, 3000, 'white-toast');
            }
        });
    </script>


{% endblock %}