apps/negocios/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^negocios/$', views.negocios_view, name='negocios'),
    url(r'^negocios/registrar/$', views.registrar_negocio_view, name='registrar_negocio'),

    url(r'^negocios/buscar/$', views.buscar_negocios, name='buscar_negocios'),

    url(r'^negocios/(?P<slug>[\w-]+)/$', views.negocio_view,
        name='negocio_view'),

    url(r'^negocios/(?P<slug>[\w-]+)/dashboard/$', views.dashboard_negocio_view,
        name='dashboard'),

    url(r'^negocios/(?P<slug>[\w-]+)/citas/$', views.citas_negocio_view,
        name='citas'),

    # Calendario y citas
    url(r'^negocios/(?P<slug>[\w-]+)/calendario/$', views.calendario_negocio_view,
        name='calendario'),

    url(r'^citas/api/activar', views.ajax_activar_cita, name='ajax_activar_cita'),
    url(r'^citas/api/rechazar', views.ajax_cancelar_cita, name='ajax_cancelar_cita'),
    url(r'^eventos/api/get', views.ajax_obtener_eventos, name='ajax_obtener_eventos'),
    url(r'^eventos/api/solicitar', views.ajax_solicitar_evento, name='ajax_solicitar_evento'),
    url(r'^eventos/api/create$', views.ajax_crear_evento, name='ajax_crear_evento'),
    url(r'^eventos/api/delete$', views.ajax_eliminar_evento, name='ajax_eliminar_evento'),
    url(r'^eventos/api/update$', views.ajax_actualizar_evento, name='ajax_actualizar_evento'),

    # Configuraciones
    url(r'^negocios/(?P<slug>[\w-]+)/configurar/$', views.configurar_negocio_view,
        name='configurar_negocio'),
    url(r'^negocios/(?P<slug>[\w-]+)/configurar/contacto/$', views.configurar_contacto_negocio_view,
        name='configurar_contacto'),
    url(r'^negocios/(?P<slug>[\w-]+)/configurar/horario/$', views.configurar_horario_negocio_view,
        name='configurar_horario'),
    url(r'^negocios/(?P<slug>[\w-]+)/configurar/servicios/$', views.configurar_servicios_negocio_view,
        name='configurar_servicios'),
    url(r'^negocios/(?P<slug>[\w-]+)/configurar/galeria/$', views.configurar_galeria_negocio_view,
        name='configurar_galeria'),
    url(r'^mis-negocios/$', views.negocios_usuario_view, name='negocios_usuario'),
]

apps/usuarios/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login', views.login_view, name='login'),
    url(r'^signup', views.signup_view, name='signup'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^perfil/$', views.perfil_usuario, name='perfil_usuario'),
    url(r'^perfil/editar$', views.editar_perfil_usuario, name='editar_perfil_usuario'),
    url(r'^mis-citas$', views.citas_usuario, name='citas_usuario'),
    url(r'^suscripcion/beneficios/$', views.beneficios_view, name='beneficios'),
]

project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles import views

urlpatterns = [

    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^users/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="user-logout"),

    url(r'^', include('apps.base.urls', namespace='base_app')),
    url(r'^', include('apps.usuarios.urls', namespace='usuarios_app')),
    url(r'^', include('apps.negocios.urls', namespace='negocios_app')),
    url(r'^', include('apps.mascotas.urls', namespace='mascotas_app')),
    url(r'^', include('apps.publicidad.urls', namespace='publicidad_app')),
    url(r'^', include('apps.pagos.urls', namespace='pagos_app')),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

apps/negocios/models.py
import os
from datetime import datetime

from django.db import models
from django.db.models import Avg
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext as _
from geoposition.fields import GeopositionField
from imagekit.models import ProcessedImageField
from pilkit.processors import ResizeToFit


def galeria_negocio_upload_to(instance, filename):
    return "galerias/{nombre}/{file}".format(nombre=instance.negocio.pk, file=filename)


class CategoriasNegocio(models.Model):
    nombre_publico = models.CharField(max_length=120)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return self.nombre_publico

    class Meta:
        verbose_name = 'Categoria de Negocio'
        verbose_name_plural = 'Categorias de Negocios'


class Negocio(models.Model):
    usuario = models.ForeignKey('usuarios.Usuario')
    nombre = models.CharField(max_length=120)
    descripcion = models.TextField(null=True)
    categorias = models.ManyToManyField(CategoriasNegocio)
    ubicacion = GeopositionField(null=True)
    direccion = models.CharField(max_length=256, null=True, blank=True)
    fecha_registro = models.DateTimeField(default=datetime.now)
    slug = models.SlugField(editable=False, max_length=60)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Negocio'
        verbose_name_plural = 'Negocios'

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.nombre + "-" + str(self.fecha_registro.date()))
        super(Negocio, self).save(*args, **kwargs)

    @property
    def get_cover_image_url(self):
        if self.imagennegocio_set.filter(is_cover_image=True).count() > 0:
            return self.imagennegocio_set.filter(is_cover_image=True)[0].get_image_url
        elif self.imagennegocio_set.all().count() > 0:
            return self.imagennegocio_set.all()[0].get_image_url
        else:
            from django.contrib.staticfiles.templatetags.staticfiles import static
            return static('base/img/default.png')

    @property
    def get_cover_image(self):
        if self.imagennegocio_set.filter(is_cover_image=True).count() > 0:
            return self.imagennegocio_set.filter(is_cover_image=True)[0]
        elif self.imagennegocio_set.all().count() > 0:
            return self.imagennegocio_set.all()[0]
        else:
            return None

    @property
    def get_dias_laborales(self):
        # not work in MySQL
        return self.horariosemanalnegocio_set.distinct('dia_semana')
        # return self.horariosemanalnegocio_set.values_list('dia_semana', flat=True).distinct()

    @property
    def get_rating(self):
        if self.comentariosnegocio_set.count():
            return round(next(iter(self.comentariosnegocio_set.aggregate(Avg('calificacion')).values())), 1)
        else:
            return 0

    @property
    def tiene_suscripcion(self):
        return self.usuario.tiene_suscripcion


class HorarioSemanalNegocio(models.Model):
    negocio = models.ForeignKey(Negocio, on_delete=models.CASCADE)

    DIAS_SEMANA = (
        ('0', _(u'Domingo')),
        ('1', _(u'Lunes')),
        ('2', _(u'Martes')),
        ('3', _(u'Miércoles')),
        ('4', _(u'Jueves')),
        ('5', _(u'Viernes')),
        ('6', _(u'Sábado')),
    )

    dia_semana = models.CharField(choices=DIAS_SEMANA, max_length=2)
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()

    nota = models.TextField(blank=True)

    def __str__(self):
        return self.negocio.nombre

    class Meta:
        ordering = ['dia_semana']
        verbose_name = 'Horario de Negocio'
        verbose_name_plural = 'Horarios de Negocios'


class ContactoNegocio(models.Model):
    negocio = models.OneToOneField(Negocio, null=True, on_delete=models.CASCADE)
    web_page = models.CharField(max_length=500, blank=True)
    facebook_page = models.CharField(max_length=500, blank=True)
    twitter_page = models.CharField(max_length=500, blank=True)
    telefono = models.CharField(max_length=18, blank=True)

    def __str__(self):
        return self.negocio.nombre

    class Meta:
        verbose_name = 'Contacto de Negocio'
        verbose_name_plural = 'Contacto de negocioes'


class ImagenNegocio(models.Model):
    negocio = models.ForeignKey(Negocio, on_delete=models.CASCADE)
    imagen = ProcessedImageField(upload_to=galeria_negocio_upload_to,
                                 format='JPEG',
                                 processors=[ResizeToFit(1920, 1080)],
                                 options={'quality': 80})

    fecha_creacion = models.DateTimeField(auto_now_add=True, null=True)
    # fecha_modificacion = models.DateTimeField(auto_now=True)
    is_cover_image = models.BooleanField(default=False)

    def __str__(self):
        return self.negocio.nombre + ': ' + os.path.basename(self.imagen.name)

    class Meta:
        verbose_name = 'Imagen de Negocio'
        verbose_name_plural = 'Imágenes de Negocios'

    def save(self, *args, **kwargs):
        if self.is_cover_image:
            other_cover_image = ImagenNegocio.objects.filter(negocio=self.negocio).filter(is_cover_image=True)
            for image in other_cover_image:
                image.is_cover_image = False
                image.save()

        super(ImagenNegocio, self).save()

    @property
    def get_image_filename(self):
        return os.path.basename(self.imagen.name)

    @property
    def get_image_url(self):
        if self.imagen:
            return self.imagen.url
        else:
            from django.contrib.staticfiles.templatetags.staticfiles import static
            return static('base/img/default.png')


class ComentariosNegocio(models.Model):
    negocio = models.ForeignKey(Negocio, on_delete=models.CASCADE)
    usuario = models.ForeignKey('usuarios.Usuario')
    texto = models.TextField()
    CALIFICACIONES = ((5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1'))
    calificacion = models.IntegerField(choices=CALIFICACIONES, null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    aprobado = models.BooleanField(default=True)

    def __str__(self):
        return self.negocio.nombre + ': ' + str(self.calificacion)

    def aprobar(self):
        self.aprobado = True
        self.save()

    class Meta:
        verbose_name = 'Comentario de Negocio'
        verbose_name_plural = 'Comentarios de Negocios'
        ordering = ["-fecha_creacion"]


class ServiciosNegocio(models.Model):
    negocio = models.ForeignKey(Negocio, on_delete=models.CASCADE)
    nombre_publico = models.CharField(max_length=120)
    descripcion = models.TextField(blank=True)
    precio = models.DecimalField(decimal_places=2, max_digits=6, null=True, blank=True)
    TIPOS_PRECIO = (('1', 'Desde'), ('2', 'Fijo'))
    tipo_precio = models.CharField(max_length=2, choices=TIPOS_PRECIO, default='1')
    tiempo_aprox_minutos = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.negocio.nombre + ': ' + self.nombre_publico

    class Meta:
        verbose_name = 'Servicio de Negocio'
        verbose_name_plural = 'Servicios de Negocios'


class Evento(models.Model):
    negocio = models.ForeignKey(Negocio, on_delete=models.CASCADE, null=True)
    titulo = models.CharField(max_length=256)
    fecha_inicio = models.DateTimeField()
    fecha_fin = models.DateTimeField(null=True)
    all_day = models.BooleanField(default=False)
    notas = models.TextField(blank=True)
    color = models.CharField(max_length=10)

    def __str__(self):
        return self.negocio.nombre + ': ' + str(self.fecha_inicio)

    class Meta:
        verbose_name = 'Evento de Negocio'
        verbose_name_plural = 'Eventos de Negocios'


class SolicitudEvento(models.Model):
    negocio = models.ForeignKey(Negocio, on_delete=models.CASCADE, null=True)
    mascota = models.ForeignKey('mascotas.Mascota', null=True)
    servicio = models.ForeignKey(ServiciosNegocio, blank=True, null=True)
    evento = models.OneToOneField(Evento, null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True, null=True)
    fecha = models.DateTimeField()
    ESTADOS_SOLICITUD = (('1', 'Pendiente'), ('2', 'Aceptado'), ('3', 'Cancelado'))
    estado = models.CharField(max_length=2, choices=ESTADOS_SOLICITUD, default='1')

    def __str__(self):
        return self.negocio.nombre + ': ' + str(self.fecha)

    class Meta:
        verbose_name = 'Solicitud de Cita'
        verbose_name_plural = 'Solicitudes de Cita'


# Receive the pre_delete signal and delete the file associated with the model instance.
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver


@receiver(pre_delete, sender=ImagenNegocio)
def mymodel_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.imagen.delete(False)

apps/negocios/forms.py
from django import forms
from django.forms import BaseModelFormSet

from .models import Negocio, CategoriasNegocio, ContactoNegocio, HorarioSemanalNegocio, ServiciosNegocio, ImagenNegocio, \
    ComentariosNegocio


class NegocioForm(forms.ModelForm):
    categorias = forms.ModelMultipleChoiceField(required=True,
                                                queryset=CategoriasNegocio.objects.all().order_by('nombre_publico'))

    class Meta:
        model = Negocio
        fields = ['categorias', 'nombre', 'descripcion', 'ubicacion']
        widgets = {
            'nombre': forms.TextInput(attrs={
                'required': True,
                'minlength': 4,
                'class': 'validate'
            }),
            'categorias': forms.CheckboxSelectMultiple(attrs={
                'required': True,
                'class': 'validate'
            }),
            'descripcion': forms.Textarea(attrs={
                'class': 'materialize-textarea validate',
                'required': True,
                'minlength': 18,
                'maxlength': 140,
                'length': 140,
            }),
        }
        labels = {
            'nombre': 'Nombre',
            'descripcion': 'Descripción',
            'categorias': 'Categorías',
            'ubicacion': ''
        }


class ContactoNegocioForm(forms.ModelForm):
    class Meta:
        model = ContactoNegocio
        fields = ['web_page', 'facebook_page', 'twitter_page', 'telefono']
        labels = {
            'web_page': 'Página web',
            'facebook_page': 'Página de Facebook',
            'twitter_page': 'Página de Twitter',
            'telefono': 'Teléfono'
        }


class HorarioNegocioForm(forms.ModelForm):
    class Meta:
        model = HorarioSemanalNegocio
        fields = ('dia_semana', 'hora_inicio', 'hora_fin')

        widgets = {
            'dia_semana': forms.Select(attrs={
                'class': 'select-dia-semana',
                'required': True
            }),
            'hora_inicio': forms.TimeInput(format='%I:%M %p', attrs={
                'class': 'timepicker',
                'required': True
            }),
            'hora_fin': forms.TimeInput(format='%I:%M %p', attrs={
                'class': 'timepicker',
                'required': True
            })
        }

        labels = {
            'dia_semana': '',
        }


class ServiciosNegocioForm(forms.ModelForm):
    class Meta:
        model = ServiciosNegocio
        fields = ('nombre_publico', 'descripcion', 'tipo_precio', 'precio', 'tiempo_aprox_minutos')

        widgets = {
            'nombre_publico': forms.TextInput(attrs={
                'required': True
            }),
            'descripcion': forms.Textarea(attrs={
                'class': 'materialize-textarea',
                'required': True,
                'minlength': 18,
                'maxlength': 280,
            }),
            'tipo_precio': forms.Select(attrs={
                'required': True
            }),
            'precio': forms.TextInput(attrs={
                'required': False
            }),
            'tiempo_aprox_minutos': forms.TextInput(attrs={
                'required': False
            }),
        }

        labels = {
            'nombre_publico': 'Nombre del servicio',
            'descripcion': 'Descripción',
            'tipo_precio': 'Tipo de precio',
            'precio': 'Precio',
            'tiempo_aprox_minutos': 'Duración (minutos)',
        }


class GaleriaNegocioForm(forms.ModelForm):
    class Meta:
        model = ImagenNegocio
        fields = ('imagen', 'is_cover_image')
        labels = {
            'is_cover_image': '¿Foto principal?'
        }


class BaseHorarioFormSet(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        self.negocio = kwargs.pop('negocio')
        super(BaseHorarioFormSet, self).__init__(*args, **kwargs)
        self.queryset = HorarioSemanalNegocio.objects.filter(negocio=self.negocio)


class BaseServiciosFormSet(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        self.negocio = kwargs.pop('negocio')
        super(BaseServiciosFormSet, self).__init__(*args, **kwargs)
        self.queryset = ServiciosNegocio.objects.filter(negocio=self.negocio)


class BaseGaleriaFormSet(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        self.negocio = kwargs.pop('negocio')
        super(BaseGaleriaFormSet, self).__init__(*args, **kwargs)
        self.queryset = ImagenNegocio.objects.filter(negocio=self.negocio)


class ComentariosNegocioForm(forms.ModelForm):
    class Meta:
        model = ComentariosNegocio
        fields = ['calificacion', "texto"]

        widgets = {
            'calificacion': forms.RadioSelect(attrs={
                'required': True
            }),
            "texto": forms.Textarea(attrs={
                'class': 'materialize-textarea',
                'required': True,
            }),
        }

templates/negocios/configuraciones_negocio/base_configuracion_negocio.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}

{% block title %}
    Editar perfil de {{ negocio.nombre }}
{% endblock %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'base/css/clockpicker/materialize.clockpicker.css' %}">

    {% block styles_configurar %}

    {% endblock %}
{% endblock %}


{% block content %}
    <nav class="white hide-on-small-and-down nav-breadcrumbs">
        <div class="container">
            <div class="nav-wrapper">
                <a href="{% url 'negocios_app:negocios_usuario' %}" class="breadcrumb black-text">Mis
                    negocios</a>
                <a href="{% url 'negocios_app:dashboard' negocio.slug %}"
                   class="breadcrumb black-text">{{ negocio.nombre }}</a>
                <a href="javascript:void(0);" class="breadcrumb black-text">Editar perfil</a>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="section">
                <div class="col s12 m8 m-t-sm">
                    <h5 class="no-top-margins"><i class="material-icons">settings</i>Editar perfil de <a
                            href="{% url 'negocios_app:negocio_view' negocio.slug %}">{{ negocio.nombre }}</a></h5>
                </div>
                <div class="col s12 m4">
                    <a class="waves-effect waves-light btn right btn-block hiddendiv" id="btn-guardar-cambios">Guardar
                        cambios</a>
                </div>
                <div class="col s12">
                    <p>{{ error }}</p>
                </div>
            </div>

            <div class="col s12 m3">
                {% include 'negocios/configuraciones_negocio/base_menu_configuraciones.html' %}
            </div>
            <div class="col s12 m9">
                <div class="card">
                    {% block config_form %}

                    {% endblock %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block scripts %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.min.js"></script>
    <script src="{% static 'negocios/js/configurar_negocio.js' %}"></script>

    {% if success %}
        <script>
            $(document).ready(function () {
                var $toastContent = $('<span><i class="material-icons">check</i> Se ha guardado correctamente</span>');
                Materialize.toast($toastContent, 3000, 'white-toast rounded');
            });
        </script>
    {% endif %}
    {% block scripts_configurar %}

    {% endblock %}
{% endblock %}

templates/negocios/configuraciones_negocio/base_menu_configuraciones.html
{% load static from staticfiles %}
<style>
    .material-icons {
        font-size: inherit;
    }
</style>
<div class="collection hide-on-small-only " id="menu-configuraciones">
    <a class="collection-item" href="{% url 'negocios_app:configurar_negocio' negocio.slug %}">
        Básico
    </a>
    <a class="collection-item" href="{% url 'negocios_app:configurar_servicios' negocio.slug %}">
        Servicios
    </a>
    <a class="collection-item" href="{% url 'negocios_app:configurar_galeria' negocio.slug %}">
        Galería
    </a>
    <a class="collection-item" href="{% url 'negocios_app:configurar_horario' negocio.slug %}">
        Horario <span class="new badge rank bold" data-badge-caption="">Premium</span>
    </a>
    <a class="collection-item" href="{% url 'negocios_app:configurar_contacto' negocio.slug %}">
        Contacto <span class="new badge rank bold" data-badge-caption="">Premium</span>
    </a>
</div>

<div class="hide-on-med-and-up">
    <!-- Dropdown Trigger -->
    <a class='dropdown-button waves-effect waves-light btn-flat center-align' href='#' data-activates='dropdown1'
       style="width: 100%;">Configuraciones<i class="material-icons right">arrow_drop_down</i></a>

    <!-- Dropdown Structure -->
    <ul id='dropdown1' class='dropdown-content'>
        <li>
            <a class="collection-item" href="{% url 'negocios_app:configurar_negocio' negocio.slug %}">
                Básico
            </a>
        </li>
        <li>
            <a class="collection-item" href="{% url 'negocios_app:configurar_servicios' negocio.slug %}">
                Servicios
            </a>
        </li>
        <li>
            <a class="collection-item" href="{% url 'negocios_app:configurar_galeria' negocio.slug %}">
                Galería
            </a>
        </li>
        <li>
            <a class="collection-item" href="{% url 'negocios_app:configurar_horario' negocio.slug %}">
                Horario <span class="new badge rank bold" data-badge-caption="">Premium</span>
            </a>
        </li>
        <li>
            <a class="collection-item" href="{% url 'negocios_app:configurar_contacto' negocio.slug %}">
                Contacto <span class="new badge rank bold" data-badge-caption="">Premium</span>
            </a>
        </li>
    </ul>
</div>

templates/negocios/configuraciones_negocio/configurar_basico_negocio.html
{% extends 'negocios/configuraciones_negocio/base_configuracion_negocio.html' %}
{% load static from staticfiles %}

{% block config_form %}
    <form action="{% url 'negocios_app:configurar_negocio' negocio.slug %}" method="POST">
        {% csrf_token %}
        <div class="card-content">
            <div class="row">
                <div class="col s12">
                    <h5>Básico</h5>
                    {% for error in negocio_form.non_field_errors %}
                        <p class="red-text text-lighten-1">{{ error }}</p>
                    {% endfor %}
                </div>
                {{ negocio_form.media }}
                {% for field in negocio_form %}
                    <div class="input-field col s12">
                        {{ field }}
                        {{ field.label_tag }}
                        {% for error in field.errors %}
                            <p class="text-error">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endfor %}
                <input type="hidden" name="direccion" id="input_direccion" value="{{ negocio.direccion }}">
            </div>

        </div>
        <div class="card-action">
            <button class="btn waves-effect waves-light accent" type="submit"
                    name="guardar_contacto" id="btn-login-submit">
                Guardar negocio
                <i class="material-icons right">send</i>
            </button>
        </div>
    </form>
{% endblock %}

{% block scripts_configurar %}
    <script src="{% static 'base/js/custom_geoposition_field.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('select#id_categorias').material_select();
        });
        $('form').on('submit', function () {
            $('#input_direccion').val($('.geoposition-address').text());
        });
    </script>
{% endblock %}

templates/negocios/configuraciones_negocio/configurar_contacto_negocio.html
{% extends 'negocios/configuraciones_negocio/base_configuracion_negocio.html' %}
{% load static from staticfiles %}

{% block config_form %}
    {% if user.tiene_suscripcion %}
        <form action="{% url 'negocios_app:configurar_contacto' negocio.slug %}" method="POST">
            {% csrf_token %}
            <div class="card-content">
                <div class="row">
                    <div class="col s12">
                        <h5>Contacto</h5>
                        {% for error in contacto_negocio_form.non_field_errors %}
                            <p class="red-text text-lighten-1">{{ error }}</p>
                        {% endfor %}
                    </div>
                    {% for field in contacto_negocio_form %}
                        <div class="input-field col s12">
                            {{ field.label_tag }}
                            {{ field }}
                            {% for error in field.errors %}
                                <p class="text-error">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="card-action">
                <button class="btn waves-effect waves-light accent" type="submit"
                        name="guardar_contacto" id="btn-login-submit">
                    Guardar contacto
                    <i class="material-icons right">send</i>
                </button>
            </div>
        </form>
    {% else %}
        <div class="card-content">
            <h5>
                Obten tu suscripción para poder agregar tu informacion de contacto al perfil.
            </h5>

            <a class="btn rank" href="{% url 'usuarios_app:beneficios' %}">ver más</a>

        </div>
    {% endif %}
{% endblock %}

templates/negocios/configuraciones_negocio/configurar_galeria_negocio.html
{% extends 'negocios/configuraciones_negocio/base_configuracion_negocio.html' %}
{% load static from staticfiles %}

{% block styles_configurar %}
    <link rel="stylesheet" href="{% static 'base/css/jquery-filer/jquery.filer.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/jquery-filer/themes/jquery.filer-dragdropbox-theme.css' %}">
    <style>
        [type="radio"]:not(:checked) + label, [type="radio"]:checked + label {
            top: 0;
            left: -10px;
        }
    </style>
{% endblock %}

{% block config_form %}
    <form action="{% url 'negocios_app:configurar_galeria' negocio.slug %}" method="POST" id="galeria-form"
          enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card-content">

            <h5>Galeria</h5>

            {% for error in galeria_negocio_form.non_field_errors %}
                <p class="red-text text-lighten-1">{{ error }}</p>
            {% endfor %}

            <div class="row m-b-none">
                <div class="col s12 input-field">
                    <input type="file" accept="image/*" name="imagen" id="imagen">
                </div>
            </div>
        </div>
        <div class="card-action">
            <button class="btn waves-effect waves-light accent" type="submit"
                    name="guardar_galeria" id="btn-login-submit">
                Guardar galeria
                <i class="material-icons right">send</i>
            </button>
        </div>
    </form>
{% endblock %}

{% block scripts_configurar %}
    <script src="{% static 'base/js/jquery-filer/jquery.filer.min.js' %}"></script>
    <script src="{% static 'negocios/js/configurar_galeria.js' %}"></script>

    <script>
        $(function () {
            $('#imagen').filer({
                changeInput: filer_default_opts.changeInput2,
                showThumbs: true,
                theme: "dragdropbox",
                templates: filer_default_opts.templates,
                extensions: ['jpg', 'jpeg', 'png', 'gif'],
                addMore: true,
                files: [
                    {% for imagen in imagenes %}
                        {
                            "name": "{{ imagen.get_image_filename }}",
                            "type": "image/jpg",
                            "file": "{{ imagen.get_image_url }}",
                            "url": "{{ imagen.get_image_url }}",
                        }{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                ],
                captions: filer_default_opts.captions
            });

            $('input[name="is_cover"][value="{{ cover.get_image_filename }}"]').attr('checked', true);
        })
    </script>
{% endblock %}