apps/negocios/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^negocios/$', views.negocios_view, name='negocios'),
    url(r'^negocios/registrar/$', views.registrar_negocio_view, name='registrar_negocio'),

    url(r'^negocios/buscar/$', views.buscar_negocios, name='buscar_negocios'),

    url(r'^negocios/(?P<slug>[\w-]+)/$', views.negocio_view,
        name='negocio_view'),

    url(r'^negocios/(?P<slug>[\w-]+)/dashboard/$', views.dashboard_negocio_view,
        name='dashboard'),

    url(r'^negocios/(?P<slug>[\w-]+)/citas/$', views.citas_negocio_view,
        name='citas'),

    # Calendario y citas
    url(r'^negocios/(?P<slug>[\w-]+)/calendario/$', views.calendario_negocio_view,
        name='calendario'),

    url(r'^citas/api/activar', views.ajax_activar_cita, name='ajax_activar_cita'),
    url(r'^citas/api/rechazar', views.ajax_cancelar_cita, name='ajax_cancelar_cita'),
    url(r'^eventos/api/get', views.ajax_obtener_eventos, name='ajax_obtener_eventos'),
    url(r'^eventos/api/solicitar', views.ajax_solicitar_evento, name='ajax_solicitar_evento'),
    url(r'^eventos/api/create$', views.ajax_crear_evento, name='ajax_crear_evento'),
    url(r'^eventos/api/delete$', views.ajax_eliminar_evento, name='ajax_eliminar_evento'),
    url(r'^eventos/api/update$', views.ajax_actualizar_evento, name='ajax_actualizar_evento'),

    # Configuraciones
    url(r'^negocios/(?P<slug>[\w-]+)/configurar/$', views.configurar_negocio_view,
        name='configurar_negocio'),
    url(r'^negocios/(?P<slug>[\w-]+)/configurar/contacto/$', views.configurar_contacto_negocio_view,
        name='configurar_contacto'),
    url(r'^negocios/(?P<slug>[\w-]+)/configurar/horario/$', views.configurar_horario_negocio_view,
        name='configurar_horario'),
    url(r'^negocios/(?P<slug>[\w-]+)/configurar/servicios/$', views.configurar_servicios_negocio_view,
        name='configurar_servicios'),
    url(r'^negocios/(?P<slug>[\w-]+)/configurar/galeria/$', views.configurar_galeria_negocio_view,
        name='configurar_galeria'),
    url(r'^mis-negocios/$', views.negocios_usuario_view, name='negocios_usuario'),
]

apps/pagos/urls.py
# coding=utf-8
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^pagos/test/$', "apps.pagos.views.pago_suscripcion", name='testPago'),
    url(r'^pagos/verificar/$', "apps.pagos.views.verificacion", name='Verificacion'),
    url(r'^pagos/completado/$', "apps.pagos.views.completado", name='PagoCompleto'),
    url(r'^pagos/api/crear$', "apps.pagos.views.ajax_crear_pago", name='ajax_crear_pago'),
]

apps/usuarios/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login', views.login_view, name='login'),
    url(r'^signup', views.signup_view, name='signup'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^perfil/$', views.perfil_usuario, name='perfil_usuario'),
    url(r'^perfil/editar$', views.editar_perfil_usuario, name='editar_perfil_usuario'),
    url(r'^mis-citas$', views.citas_usuario, name='citas_usuario'),
    url(r'^suscripcion/beneficios/$', views.beneficios_view, name='beneficios'),
]

project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles import views

urlpatterns = [

    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^users/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="user-logout"),

    url(r'^', include('apps.base.urls', namespace='base_app')),
    url(r'^', include('apps.usuarios.urls', namespace='usuarios_app')),
    url(r'^', include('apps.negocios.urls', namespace='negocios_app')),
    url(r'^', include('apps.mascotas.urls', namespace='mascotas_app')),
    url(r'^', include('apps.publicidad.urls', namespace='publicidad_app')),
    url(r'^', include('apps.pagos.urls', namespace='pagos_app')),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

apps/negocios/views.py
# coding=utf-8
import json
import logging
from datetime import datetime, timedelta, date

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.forms import modelformset_factory
from django.http import Http404
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import dateparse

from apps.base.functions import custom_redirect, check_owner
from apps.mascotas.models import Mascota
from apps.usuarios.correos import enviar_correo
from apps.usuarios.models import Usuario, SuscripcionUsuario
from .forms import NegocioForm, ContactoNegocioForm, HorarioNegocioForm, BaseHorarioFormSet, ServiciosNegocioForm, \
    BaseServiciosFormSet, ComentariosNegocioForm
from .models import Negocio, ContactoNegocio, HorarioSemanalNegocio, ServiciosNegocio, ImagenNegocio, Evento, \
    SolicitudEvento, CategoriasNegocio

logger = logging.getLogger(__name__)


def negocios_view(request):
    negocios = Negocio.objects.all()
    return render(request, 'negocios/negocios.html', {'negocios': negocios})


def buscar_negocios__old(request):
    categorias = CategoriasNegocio.objects.all().order_by('nombre_publico')

    lista_negocios = Negocio.objects.all()

    if 'cat' in request.GET:
        lista_negocios = lista_negocios.filter(categorias__id=request.GET['cat'])

    if request.method == 'POST':

        if request.POST['latitud'] and request.POST['longitud']:
            import math

            lat = float(request.POST['latitud'])
            long = float(request.POST['longitud'])

            # Haversine formula = https://en.wikipedia.org/wiki/Haversine_formula
            R = 6378.1  # earth radius
            bearing = 1.57  # 90 degrees bearing converted to radians.
            distance = 5  # distance in km

            lat1 = math.radians(lat)  # lat in radians
            long1 = math.radians(long)  # long in radians

            lat2 = math.asin(math.sin(lat1) * math.cos(distance / R) +
                             math.cos(lat1) * math.sin(distance / R) * math.cos(bearing))

            long2 = long1 + math.atan2(math.sin(bearing) * math.sin(distance / R) * math.cos(lat1),
                                       math.cos(distance / R) - math.sin(lat1) * math.sin(lat2))

            lat2 = math.degrees(lat2)
            long2 = math.degrees(long2)

            negocios = lista_negocios.exclude(ubicacion__isnull=True).exclude(ubicacion__exact='')

            lista_negocios = []

            for negocio in negocios:
                if negocio.ubicacion:
                    latitud = negocio.ubicacion.latitude
                    longitud = negocio.ubicacion.longitude

                    if lat1 <= latitud <= lat2 or long1 <= longitud <= long2:
                        lista_negocios.append(negocio)

            return render(request, 'negocios/buscar_negocios.html', {'negocios': lista_negocios,
                                                                     'categorias': categorias,
                                                                     'latitud': lat,
                                                                     'longitud': long})

    return render(request, 'negocios/buscar_negocios.html', {'negocios': lista_negocios,
                                                             'categorias': categorias,})


def buscar_negocios(request):
    categorias = CategoriasNegocio.objects.all().order_by('nombre_publico')

    negocios = Negocio.objects.all()

    if request.method == 'POST':

        query = request.POST["query"]
        categoria = None

        try:
            if 'categoria' in request.POST and request.POST['categoria'] != '':
                negocios = negocios.filter(categorias__id=request.POST['categoria'])
                categoria = CategoriasNegocio.objects.get(id=request.POST['categoria'])

            if query != "":
                negocios = negocios.filter(
                        Q(nombre__icontains=query) |
                        Q(descripcion__icontains=query)
                ).distinct()

            if request.POST['latitud'] != '' and request.POST['longitud'] != '':
                import math

                lat = math.radians(float(request.POST['latitud']))
                long = math.radians(float(request.POST['longitud']))
                R = 6378.1  # earth radius
                distance = 5  # distance in km
                # negocios = negocios.exclude(ubicacion__isnull=True).exclude(ubicacion__exact='')

                lista_negocios = []
                for negocio in negocios:
                    if negocio.ubicacion:
                        latitud = math.radians(float(negocio.ubicacion.latitude))
                        longitud = math.radians(float(negocio.ubicacion.longitude))
                        distancia = R * (
                            math.acos(
                                    (
                                        math.cos(
                                                lat
                                        ) * math.cos(
                                                latitud
                                        ) * math.cos(
                                                long - longitud
                                        )
                                    ) + (
                                        math.sin(
                                                lat
                                        ) * math.sin(
                                                latitud
                                        )
                                    )
                            )
                        )
                        if distancia <= distance:
                            lista_negocios.append(negocio)
                if len(lista_negocios) > 0:
                    lista_negocios = sorted(lista_negocios, key=lambda t: t.get_rating)
                    # print("filtrados")
            else:
                lista_negocios = negocios
            return render(request, 'negocios/buscar_negocios.html', {'negocios': lista_negocios,
                                                                     'categorias': categorias,
                                                                     'ubicacion': request.POST['ubicacion'],
                                                                     'categoria': categoria,
                                                                     'query': query})
        except Exception as e:
            pass  # print(e.args)
    # print("todos")
    return render(request, 'negocios/buscar_negocios.html', {'negocios': negocios,
                                                             'categorias': categorias,})


def negocio_view(request, slug):
    try:
        negocio = get_object_or_404(Negocio, slug=slug)
    except Negocio.MultipleObjectsReturned:
        negocio = Negocio.objects.filter(slug=slug).first()

    comentario_form = ComentariosNegocioForm()
    comentarios_disponibles = True
    comentario_usuario = None
    if request.user.is_anonymous():
        comentarios_disponibles = False
    elif negocio.comentariosnegocio_set.filter(usuario=Usuario.objects.get(id=request.user.id)).exists():
        comentarios_disponibles = False
        comentario_usuario = negocio.comentariosnegocio_set.filter(usuario=request.user).first()

    if request.method == 'POST':
        if comentarios_disponibles:
            comentario_form = ComentariosNegocioForm(request.POST)
            if comentario_form.is_valid():
                comentario = comentario_form.save(commit=False)
                comentario.usuario = request.user
                comentario.negocio = negocio
                comentario.save()
                return redirect(reverse('negocios_app:negocio_view', kwargs={'slug': slug}))

    return render(request, 'negocios/negocio.html', {'negocio': negocio,
                                                     'es_dueno': check_owner(request.user, negocio),
                                                     'comentario_form': comentario_form,
                                                     'comentarios_disponibles': comentarios_disponibles,
                                                     'comentario_usuario': comentario_usuario or None,})


@login_required
def negocios_usuario_view(request):
    negocios = Negocio.objects.filter(usuario=request.user)
    return render(request, 'negocios/negocios_usuario.html', {'negocios': negocios})


@login_required(login_url='/signup')
def registrar_negocio_view(request):
    """
    if Negocio.objects.filter(usuario=request.user).exists():
        return redirect(reverse('base_app:home'))
    """
    negocio_form = NegocioForm()
    if request.method == 'POST':
        negocio_form = NegocioForm(request.POST, request.FILES)
        if negocio_form.is_valid():
            negocio = negocio_form.save(commit=False)
            negocio.usuario = Usuario.objects.get(pk=request.user.pk)
            negocio.direccion = request.POST['direccion']
            negocio = negocio_form.save()
            enviar_correo(destino=negocio.usuario.email,
                          asunto='miPetdate: Contacto para Suscripción',
                          template='contacto_suscripcion')
            ImagenNegocio.objects.create(negocio=negocio, imagen=request.FILES['imagen_principal'], is_cover_image=True)

            if not negocio.usuario.periodo_prueba:
                # Creando su periodo de prueba
                from django.conf import settings
                try:
                    if not negocio.usuario.suscripcionusuario:
                        SuscripcionUsuario.objects.create(usuario=negocio.usuario, prueba=True,
                                                          estado='1',

templates/negocios/calendario_negocio.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}

{% block title %}
    Calendario {{ negocio.nombre }}
{% endblock %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'base/css/clockpicker/materialize.clockpicker.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/colorpicker/palette-color-picker.css' %}">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.9.0/fullcalendar.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.9.0/fullcalendar.print.css"
          media="print">
    <link rel="stylesheet" href="{% static 'negocios/css/calendar.css' %}">
{% endblock %}


{% block content %}
    <nav class="white hide-on-small-and-down nav-breadcrumbs">
        <div class="container">
            <div class="nav-wrapper">
                <div class="col s12">
                    <a href="{% url 'negocios_app:negocios_usuario' %}" class="breadcrumb black-text">Mis negocios</a>
                    <a href="{% url 'negocios_app:dashboard' negocio.slug %}"
                       class="breadcrumb black-text">{{ negocio.nombre }}</a>
                    <a href="javascript:void(0);" class="breadcrumb black-text">Calendario</a>
                </div>
            </div>
        </div>
    </nav>
    <div class="container section">
        <div class="row section">
            <div class="col s12">
                <div id="calendar">

                </div>
            </div>
        </div>
    </div>

    <div id="modal_evento" class="modal modal-fixed-footer" style="top: 5% !important; height: 90%; max-height: 90%;">
        <div class="modal-content">
            <div class="row">
                <div class="col s12">
                    <h4><i class="material-icons deep-orange-text">event</i><span id="titulo_modal"></span></h4>
                </div>

                <form action="" id="form_evento">
                    <div class="input-field col s12">
                        <input id="titulo_evento" type="text" name="titulo_evento" class="validate" required>
                        <label for="titulo_evento">Nombre del evento</label>
                    </div>
                    <div class="input-field col s12">
                        <input id="fecha_evento" type="date" name="fecha_evento" class="datepicker" required>
                        <label for="fecha_evento">Fecha</label>
                    </div>
                    <div class="input-field col s6">
                        <input id="hora_evento" type="text" name="hora_evento" class="timepicker validate" required>
                        <label for="hora_evento">Hora Inicio</label>
                    </div>

                    <div class="input-field col s6">
                        <input id="hora_fin_evento" type="text" name="hora_fin_evento" class="timepicker validate">
                        <label for="hora_fin_evento">Hora Fin</label>
                    </div>

                    <div class="input-field col s6">
                        <input id="color_evento" type="hidden" name="color_evento" value="#5C6BC0" required>
                    </div>

                    <div class="input-field col s6">
                        <input id="allday_evento" type="checkbox" name="allday_evento">
                        <label for="allday_evento" style="top: 0 !important; left: 0 !important;">Todo el día?</label>
                    </div>

                    <div class="input-field col s12">
                        <textarea id="notas_evento" class="materialize-textarea" name="notas_evento"></textarea>
                        <label for="notas_evento">Notas adicionales</label>
                    </div>
                </form>
            </div>
        </div>
        <div class="modal-footer">
            <a href="javascript:void(0);" class="btn-flat left"
               id="btn_eliminar_evento"><i
                    class="material-icons left">delete</i>Eliminar</a>

            <a href="javascript:void(0);" class="waves-effect waves-light btn teal"
               id="btn_guardar_evento">Aceptar</a>
            <a href="javascript:void(0);" class="modal-action modal-close btn-flat">Cancelar</a>
        </div>
    </div>
    <div id="modal_confirmar_eliminar_evento" class="modal">
        <div class="modal-content">
            <h4>¿Seguro que deseas eliminar el evento?</h4>
        </div>
        <div class="modal-footer">
            <a href="javascript:void(0);" id="btn_confirmar_eliminar_evento"
               class="modal-action modal-close waves-effect waves-light btn red"><i
                    class="material-icons right">delete</i>Eliminar</a>
            <a href="javascript:void(0);" class="modal-action modal-close btn-flat">Cancelar</a>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    <script src="{% static 'base/js/clockpicker/materialize.clockpicker.js' %}"></script>
    <script src="{% static 'base/js/clockpicker/es_ES.js' %}"></script>
    <script src="{% static 'base/js/colorpicker/palette-color-picker.min.js' %}"></script>
    <script src="{% static 'base/js/moment/moment.js' %}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.9.0/fullcalendar.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.9.0/lang-all.js"></script>

    <script src="{% static 'negocios/js/calendario_negocio.js' %}"></script>

    <script>

        var eventoSourceObj = {
            url: '{% url 'negocios_app:ajax_obtener_eventos' %}',
            type: 'get',
            data: {
                id_negocio: '{{ negocio.id }}'
            },
            error: function (xhr, errmsg, err) {
                $toastContent = $('<span><i class="material-icons">check</i> Hubo un problema al cargar los eventos</span>');
                Materialize.toast($toastContent, 1000, 'red lighten-1 rounded');
                // console.log("error " + xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
            }
        };

        function ajaxCrearEvento(event) {
            var dataObject = {};
            dataObject.event = event;

            // Resolvemos el problema con UTC
            dataObject.event.start = moment(event.start).format();
            dataObject.event.end = moment(event.end).format();

            dataObject.id_negocio = "{{ negocio.id }}";
            var dataJson = JSON.stringify(dataObject);
            $.ajax({
                url: "{% url 'negocios_app:ajax_crear_evento' %}",
                data: dataJson,
                contentType: "application/json; charset=utf-8",
                type: "POST",
                success: function (data, textStatus, jqXHR) {
                    var $toastContent = $('<span><i class="material-icons">check</i> Cambios guardados correctamente</span>');
                    Materialize.toast($toastContent, 1000, 'white-toast rounded');
                },
                error: function (xhr, errmsg, err) {
                    var $toastContent;
                    if (xhr.status == 200) {
                        $toastContent = $('<span><i class="material-icons">check</i> Cambios guardados correctamente</span>');
                        Materialize.toast($toastContent, 1000, 'white-toast rounded');
                    }
                    else {
                        $toastContent = $('<span><i class="material-icons">check</i> Hubo un problema al crear evento</span>');
                        Materialize.toast($toastContent, 1000, 'red lighten-1 rounded');
                    }
                    // console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                }
            });
        }

        function ajaxActualizarEvento(event) {
            var dataObject = {};
            dataObject.event = event;

            // Resolvemos el problema con UTC
            // dataObject.event.fecha_inicio = moment(event.start).format();
            // dataObject.event.fecha_fin = moment(event.end).format();

            dataObject.id_negocio = "{{ negocio.id }}";
            var dataJson = JSON.stringify(dataObject);
            $.ajax({
                url: "{% url 'negocios_app:ajax_actualizar_evento' %}",
                data: dataJson,
                contentType: "application/json; charset=utf-8",
                type: "post",
                success: function (data, textStatus, jqXHR) {
                    var $toastContent = $('<span><i class="material-icons">check</i> Cambios guardados correctamente</span>');
                    Materialize.toast($toastContent, 1000, 'white-toast rounded');
                },
                error: function (xhr, errmsg, err) {
                    var $toastContent;
                    if (xhr.status == 200) {
                        $toastContent = $('<span><i class="material-icons">check</i> Cambios guardados correctamente</span>');
                        Materialize.toast($toastContent, 1000, 'white-toast rounded');
                    }
                    else {
                        $toastContent = $('<span><i class="material-icons">check</i> Hubo un problema al actualizar evento</span>');
                        Materialize.toast($toastContent, 1000, 'red lighten-1 rounded');
                    }
                    // console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                }
            });
        }

        function ajaxEliminarEvento(event_id) {
            var success = false;
            $.ajax({
                url: "{% url 'negocios_app:ajax_eliminar_evento' %}",
                data: {'id_evento': event_id},
                type: "POST",
                success: function (data, textStatus, jqXHR) {
                    var $toastContent = $('<span><i class="material-icons">check</i> Cambios guardados correctamente</span>');
                    Materialize.toast($toastContent, 1000, 'white-toast rounded');
                    success = true;
                },
                error: function (xhr, errmsg, err) {
                    var $toastContent;
                    if (xhr.status == 200) {
                        $toastContent = $('<span><i class="material-icons">check</i> Cambios guardados correctamente</span>');
                        Materialize.toast($toastContent, 1000, 'white-toast rounded');
                    }
                    else {
                        $toastContent = $('<span><i class="material-icons">check</i> Hubo un problema al eliminar evento</span>');
                        Materialize.toast($toastContent, 1000, 'red lighten-1 rounded');
                    }
                    // console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                }
            });
        }
    </script>
{% endblock %}

templates/negocios/dashboard_negocio.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}

{% block title %}
    Dashboard {{ negocio.nombre }}
{% endblock %}


{% block styles %}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.9.0/fullcalendar.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.9.0/fullcalendar.print.css">
    <style>
        .dashboard-badge {
            width: 100%;
            left: 0;
            bottom: 0;
            border-radius: 0 !important;
        }
    </style>
{% endblock %}


{% block content %}
    <nav class="white hide-on-small-and-down nav-breadcrumbs">
        <div class="container">
            <div class="nav-wrapper">
                <a href="{% url 'negocios_app:negocios_usuario' %}" class="breadcrumb black-text">Mis negocios</a>
                <a href="javascript:void(0);" class="breadcrumb black-text">{{ negocio.nombre }}</a>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row section">
            <div class="col s12">
                <h4><a href="{% url 'negocios_app:negocio_view' negocio.slug %}">{{ negocio.nombre|upper }}</a></h4>
            </div>
            <div class="col s6 m4 l3">
                {% if user.tiene_suscripcion %}
                    <a href="{% url 'negocios_app:calendario' negocio.slug %}">
                {% else %}
                    <a class="modal-trigger pointer" data-target="modalsuscripcion">
                {% endif %}
                <div class="card hoverable">
                    <div class="card-content center-align p-tb-lg">
                        <h1 class="no-margins action-text">
                            <i class="material-icons">event</i>
                        </h1>
                        <h5 class="black-text">
                            Calendario
                        </h5>
                        <span class="new badge rank dashboard-badge" data-badge-caption="">Premium</span>
                    </div>
                </div>
                </a>
            </div>
            <div class="col s6 m4 l3">
                {% if user.tiene_suscripcion %}
                    <a href="{% url 'negocios_app:citas' negocio.slug %}">
                {% else %}
                    <a class="modal-trigger pointer" data-target="modalsuscripcion">
                {% endif %}
                <div class="card hoverable">
                    <div class="card-content center-align p-tb-lg">
                        <h1 class="no-margins accent-text">
                            <i class="material-icons">perm_contact_calendar</i>
                        </h1>
                        <h5 class="black-text">
                            Citas
                        </h5>
                        <span class="new badge rank dashboard-badge" data-badge-caption="">Premium</span>
                    </div>
                </div>
                </a>
            </div>

            <div class="col s6 m4 l3">
                <a href="{% url 'negocios_app:configurar_negocio' negocio.slug %}">
                    <div class="card hoverable">
                        <div class="card-content center-align p-tb-lg">
                            <h1 class="no-margins primary-text">
                                <i class="material-icons">mode_edit</i>
                            </h1>
                            <h5 class="black-text">
                                Editar perfil
                            </h5>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <!-- Modal Structure -->
    <div id="modalsuscripcion" class="modal">
        <div class="modal-content">
            <h4>¡Suscribete hoy!</h4>
            <p>Para utilizar ésta característica, debes tener una suscripción activa.</p>
        </div>
        <div class="modal-footer">
            <a href="{% url 'usuarios_app:beneficios' %}" class="btn action">Ver mas</a>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    <script>
        $(document).ready(function () {
            // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
            $('.modal').modal();
        });
        if (getUrlParameter('success')) {
            var querygetstr = $(location).attr('search');
            $('#btn-signup').attr('href', "{% url 'usuarios_app:signup' %}" + querygetstr);
            var $toastContent = $('<span><i class="material-icons left">check</i>Felicidades, has obtenido una prueba de 10 días gratis </span>');
            Materialize.toast($toastContent, 3000, 'accent rounded bold');
        }
    </script>
{% endblock %}

templates/negocios/negocios.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}


{% block title %}
    Explora
{% endblock %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'base/css/stars.css' %}">
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row section">
            <div class="col s12 center-align">
                <h2>Explora y descubre</h2>
            </div>
            {% for negocio in negocios %}
                {% include 'negocios/base_negocio_card.html' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}


{% block scripts %}

{% endblock %}